# Generated by Django 5.2.6 on 2025-10-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_alter_stakeholder_interest_alter_stakeholder_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='has_cognitive_resources',
            field=models.BooleanField(default=False, verbose_name='Cognitive'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='has_economic_resources',
            field=models.BooleanField(default=False, verbose_name='Economic'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='has_legal_resources',
            field=models.BooleanField(default=False, verbose_name='Legal'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='has_political_resources',
            field=models.BooleanField(default=False, verbose_name='Political'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='level',
            field=models.CharField(choices=[('International', 'International'), ('National', 'National'), ('Regional', 'Regional'), ('Provincial', 'Provincial'), ('Local', 'Local')], default='Local', max_length=20),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='typology',
            field=models.CharField(choices=[('Political', 'Political actors'), ('Bureaucratic', 'Bureaucratic actors'), ('Special', 'Special interests'), ('General', 'General interests'), ('Experts', 'Experts')], default='General', max_length=20),
        ),
    ]
