# Generated by Django 5.2.6 on 2025-10-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_stakeholder_has_cognitive_resources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='has_cognitive_resources',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='has_economic_resources',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='has_legal_resources',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='has_political_resources',
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='resources',
            field=models.CharField(choices=[('Political', 'Political resources'), ('Economic', 'Economic resources'), ('Legal', 'Legal resources'), ('Cognitive', 'Cognitive resources')], default='Cognitive', max_length=20),
        ),
    ]
