# Generated by Django 5.2.6 on 2025-10-13 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_remove_stakeholder_has_cognitive_resources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('CORE', 'Core Problem'), ('CAUSE', 'Cause'), ('EFFECT', 'Effect')], default='CAUSE', max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workshops.problem'),
        ),
    ]
