# Generated by Django 5.2.6 on 2025-10-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_problem_problem_type_alter_problem_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='color',
            field=models.CharField(blank=True, help_text='Select a color (e.g., #FF0000)', max_length=7, null=True),
        ),
    ]
