# Generated by Django 5.2.6 on 2025-10-30 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_problem_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('objective_type', models.CharField(choices=[('SITUATION', 'Desired Situation'), ('OBJECTIVE', 'Objective (Means)'), ('IMPACT', 'Impact (End)')], default='OBJECTIVE', max_length=10)),
                ('color', models.CharField(blank=True, help_text='Select a color (e.g., #FF0000)', max_length=7, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workshops.objective')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='workshops.project')),
            ],
        ),
    ]
