# Generated by Django 5.2.6 on 2025-11-03 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0007_objective'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('accepted', models.BooleanField(default=False)),
                ('added_by_student', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('white_cards_after', models.PositiveSmallIntegerField(default=0, help_text='0=weak ... 4=extreme')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='workshops.project')),
            ],
            options={
                'ordering': ['-accepted', 'order', 'name'],
            },
        ),
    ]
