# Generated by Django 5.2.6 on 2025-11-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0009_masterindicator_alter_indicator_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('weight', models.FloatField(default=0.0)),
                ('white_cards_after', models.PositiveIntegerField(default=0)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.indicator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='workshops.project')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SWOTEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('S', 'Strength'), ('W', 'Weakness'), ('O', 'Opportunity'), ('T', 'Threat')], max_length=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swot_entries', to='workshops.project')),
            ],
        ),
    ]
