# Generated by Django 5.2.6 on 2025-11-05 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0010_indicatorranking_swotentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SWOTItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('S', 'Strength'), ('W', 'Weakness'), ('O', 'Opportunity'), ('T', 'Threat')], max_length=1)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swot_items', to='workshops.project')),
            ],
        ),
        migrations.DeleteModel(
            name='SWOTEntry',
        ),
    ]
