# Generated by Django 5.2.6 on 2025-11-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0012_project_description_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
