# Generated by Django 5.2.6 on 2025-11-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0013_project_group_name_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='overview',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
