# Generated by Django 5.2.6 on 2025-12-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0014_project_overview_alter_project_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='objective_tree',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='scenario_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
