# Generated by Django 5.2.6 on 2026-02-03 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0015_project_objective_tree_project_scenario_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='QSortResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=64)),
                ('participant_label', models.CharField(blank=True, max_length=255)),
                ('sort_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qsort_results', to='workshops.project')),
            ],
        ),
    ]
