# Generated by Django 5.2.6 on 2026-02-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0016_qsortresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='indicator_ranking_groups',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='indicator_ranking_order',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
