# Generated by Django 5.2.6 on 2026-02-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0017_project_indicator_ranking_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='indicator_ranking_groups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='indicator_ranking_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
