# Generated by Django 5.2.6 on 2026-03-09 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0018_alter_project_indicator_ranking_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_id', models.CharField(max_length=50)),
                ('indicator_name', models.CharField(max_length=255)),
                ('data_image', models.ImageField(blank=True, null=True, upload_to='indicator_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_data', to='workshops.project')),
            ],
            options={
                'unique_together': {('project', 'indicator_id')},
            },
        ),
    ]
